version: '3.8'

services:
  web:
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python app/main.py'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
        # ? is this even safe
      - DATABASE_URL=postgresql+asyncpg://root:k4Q46wUg76@db/interns
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=k4Q46wUg76
      - POSTGRES_DB=interns

volumes:
  postgres_data:
